    -- Generated by Level Director v2.0.2 on 5/8/2013 2:46:28 PM

module(..., package.seeall)
require ("config")
require ("sprite")



imgSubFolder = ""
spriteSheets={}
spriteSets={}

if (application.LeveldirectorsettingsCredits.imagesSubfolder ~= nil) then
    imgSubFolder = application.LeveldirectorsettingsCredits.imagesSubfolder
    imgSubFolder = imgSubFolder .. "/"
end

function LoadAssets()

    local assets = {}

    ---- Asset : alex_gif ----
    assets["alex_gif"] = {}
    assets["alex_gif"].file = "alex.gif"
    assets["alex_gif"].name = "alex_gif"
    assets["alex_gif"].width = 600
    assets["alex_gif"].height = 227
    assets["alex_gif"].frame = 0
    assets["alex_gif"].frameCount = 0

    ---- Asset : alex_image_jpeg ----
    assets["alex_image_jpeg"] = {}
    assets["alex_image_jpeg"].file = "alex-image.jpeg"
    assets["alex_image_jpeg"].name = "alex_image_jpeg"
    assets["alex_image_jpeg"].width = 204
    assets["alex_image_jpeg"].height = 247
    assets["alex_image_jpeg"].frame = 0
    assets["alex_image_jpeg"].frameCount = 0

    ---- Asset : alex_info_jpeg ----
    assets["alex_info_jpeg"] = {}
    assets["alex_info_jpeg"].file = "alex-info.jpeg"
    assets["alex_info_jpeg"].name = "alex_info_jpeg"
    assets["alex_info_jpeg"].width = 204
    assets["alex_info_jpeg"].height = 247
    assets["alex_info_jpeg"].frame = 0
    assets["alex_info_jpeg"].frameCount = 0

    ---- Asset : chris_gif ----
    assets["chris_gif"] = {}
    assets["chris_gif"].file = "chris.gif"
    assets["chris_gif"].name = "chris_gif"
    assets["chris_gif"].width = 600
    assets["chris_gif"].height = 227
    assets["chris_gif"].frame = 0
    assets["chris_gif"].frameCount = 0

    ---- Asset : chris_image_jpeg ----
    assets["chris_image_jpeg"] = {}
    assets["chris_image_jpeg"].file = "chris-image.jpeg"
    assets["chris_image_jpeg"].name = "chris_image_jpeg"
    assets["chris_image_jpeg"].width = 204
    assets["chris_image_jpeg"].height = 247
    assets["chris_image_jpeg"].frame = 0
    assets["chris_image_jpeg"].frameCount = 0

    ---- Asset : chris_info_jpeg ----
    assets["chris_info_jpeg"] = {}
    assets["chris_info_jpeg"].file = "chris-info.jpeg"
    assets["chris_info_jpeg"].name = "chris_info_jpeg"
    assets["chris_info_jpeg"].width = 204
    assets["chris_info_jpeg"].height = 247
    assets["chris_info_jpeg"].frame = 0
    assets["chris_info_jpeg"].frameCount = 0

    ---- Asset : logo_gif ----
    assets["logo_gif"] = {}
    assets["logo_gif"].file = "logo.gif"
    assets["logo_gif"].name = "logo_gif"
    assets["logo_gif"].width = 600
    assets["logo_gif"].height = 227
    assets["logo_gif"].frame = 0
    assets["logo_gif"].frameCount = 0

    ---- Asset : rafael_gif ----
    assets["rafael_gif"] = {}
    assets["rafael_gif"].file = "rafael.gif"
    assets["rafael_gif"].name = "rafael_gif"
    assets["rafael_gif"].width = 600
    assets["rafael_gif"].height = 227
    assets["rafael_gif"].frame = 0
    assets["rafael_gif"].frameCount = 0

    ---- Asset : rafael_image_jpeg ----
    assets["rafael_image_jpeg"] = {}
    assets["rafael_image_jpeg"].file = "rafael-image.jpeg"
    assets["rafael_image_jpeg"].name = "rafael_image_jpeg"
    assets["rafael_image_jpeg"].width = 204
    assets["rafael_image_jpeg"].height = 247
    assets["rafael_image_jpeg"].frame = 0
    assets["rafael_image_jpeg"].frameCount = 0

    ---- Asset : rafael_info_jpeg ----
    assets["rafael_info_jpeg"] = {}
    assets["rafael_info_jpeg"].file = "rafael-info.jpeg"
    assets["rafael_info_jpeg"].name = "rafael_info_jpeg"
    assets["rafael_info_jpeg"].width = 204
    assets["rafael_info_jpeg"].height = 247
    assets["rafael_info_jpeg"].frame = 0
    assets["rafael_info_jpeg"].frameCount = 0

    ---- Asset : team_image_jpeg ----
    assets["team_image_jpeg"] = {}
    assets["team_image_jpeg"].file = "team-image.jpeg"
    assets["team_image_jpeg"].name = "team_image_jpeg"
    assets["team_image_jpeg"].width = 204
    assets["team_image_jpeg"].height = 247
    assets["team_image_jpeg"].frame = 0
    assets["team_image_jpeg"].frameCount = 0
    return assets

end -- LoadAssets

function CreateObjectFromAsset(parent, assets, assetName, x, y, xScale, yScale)

    local obj = nil

    if (assets[assetName]) then
        local asset = assets[assetName]
        if (asset.frame == 0) then
            obj = display.newImageRect(parent, imgSubFolder .. asset.file, asset.width * xScale , asset.height * yScale )
        else
            --if part of spritesheet check if it already exists
            local spriteSheet = nil
            local spriteSet = nil
            if (spriteSheets[asset.file] == nil) then
                --create new spritesheet and sprite set
                spriteSheets[asset.file] = sprite.newSpriteSheet( imgSubFolder .. asset.file, asset.width,asset.height)
                spriteSets[asset.file] = sprite.newSpriteSet(spriteSheets[asset.file], 1,asset.frameCount)				
            end
            spriteSheet = spriteSheets[asset.file]
            spriteSet = spriteSets[asset.file]
            --add animation sequences
            if (assets[assetName].animSequence) then
                for i = 1, #assets[assetName].animSequence do
                    sprite.add(spriteSet,assets[assetName].animSequence[i].name,assets[assetName].animSequence[i].startFrame,assets[assetName].animSequence[i].frameCount,assets[assetName].animSequence[i].time,assets[assetName].animSequence[i].loop)
                end
            end

            obj = sprite.newSprite(spriteSet)
            obj.currentFrame = asset.frame
        end
        obj.x = x
        obj.y = y
        if (asset.physics)then
            physics.addBody(obj, asset.physics.bodyType, asset.physics.attributes)
            if (asset.physics.isFixedRotation) then obj.isFixedRotation = asset.physics.isFixedRotation end
            if (asset.physics.isSleepingAllowed) then obj.isSleepingAllowed = asset.physics.isSleepingAllowed end
            if (asset.physics.angularDamping) then obj.angularDamping = asset.physics.angularDamping end
            if (asset.physics.linearDamping) then obj.linearDamping = asset.physics.linearDamping end
        end
    end
    return obj
end -- CreateObjectFromAsset

function CreateLevel(physics)

    display.setDefault( 'background', 105,105,105 )
    physics.setGravity(0,9.8)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "creditsScreen"

    ---- Layer : fg ----
    level.layers["fg"] = display.newGroup()
    level.layers["fg"].name = "fg"

    level.layers["fg"].objects = {}

    level.layers["fg"].objects["riverRun"] = display.newImageRect( imgSubFolder .. "logo.gif",307,117 )
    level.layers["fg"].objects["riverRun"].x = 160
    level.layers["fg"].objects["riverRun"].y = 73
    level.layers["fg"].objects["riverRun"].name = "riverRun"
    level.layers["fg"]:insert(level.layers["fg"].objects["riverRun"])

    level.layers["fg"].objects["alex"] = display.newImageRect( imgSubFolder .. "alex.gif",180,83 )
    level.layers["fg"].objects["alex"].x = 153
    level.layers["fg"].objects["alex"].y = -135
    level.layers["fg"].objects["alex"].name = "alex"
    level.layers["fg"]:insert(level.layers["fg"].objects["alex"])

    level.layers["fg"].objects["alexImage"] = display.newImageRect( imgSubFolder .. "alex-image.jpeg",139,165 )
    level.layers["fg"].objects["alexImage"].x = 67
    level.layers["fg"].objects["alexImage"].y = -289
    level.layers["fg"].objects["alexImage"].name = "alexImage"
    level.layers["fg"]:insert(level.layers["fg"].objects["alexImage"])

    level.layers["fg"].objects["alexInfo"] = display.newImageRect( imgSubFolder .. "alex-info.jpeg",134,160 )
    level.layers["fg"].objects["alexInfo"].x = 248
    level.layers["fg"].objects["alexInfo"].y = -289
    level.layers["fg"].objects["alexInfo"].name = "alexInfo"
    level.layers["fg"]:insert(level.layers["fg"].objects["alexInfo"])

    level.layers["fg"].objects["chris"] = display.newImageRect( imgSubFolder .. "chris.gif",199,92 )
    level.layers["fg"].objects["chris"].x = 160
    level.layers["fg"].objects["chris"].y = -572
    level.layers["fg"].objects["chris"].name = "chris"
    level.layers["fg"]:insert(level.layers["fg"].objects["chris"])

    level.layers["fg"].objects["chrisImage"] = display.newImageRect( imgSubFolder .. "chris-image.jpeg",125,159 )
    level.layers["fg"].objects["chrisImage"].x = 245
    level.layers["fg"].objects["chrisImage"].y = -738
    level.layers["fg"].objects["chrisImage"].name = "chrisImage"
    level.layers["fg"]:insert(level.layers["fg"].objects["chrisImage"])

    level.layers["fg"].objects["chrisInfo"] = display.newImageRect( imgSubFolder .. "chris-info.jpeg",131,165 )
    level.layers["fg"].objects["chrisInfo"].x = 83
    level.layers["fg"].objects["chrisInfo"].y = -743
    level.layers["fg"].objects["chrisInfo"].name = "chrisInfo"
    level.layers["fg"]:insert(level.layers["fg"].objects["chrisInfo"])

    level.layers["fg"].objects["raf"] = display.newImageRect( imgSubFolder .. "rafael.gif",183,79 )
    level.layers["fg"].objects["raf"].x = 164
    level.layers["fg"].objects["raf"].y = -1004
    level.layers["fg"].objects["raf"].name = "raf"
    level.layers["fg"]:insert(level.layers["fg"].objects["raf"])

    level.layers["fg"].objects["rafImage"] = display.newImageRect( imgSubFolder .. "rafael-image.jpeg",127,164 )
    level.layers["fg"].objects["rafImage"].x = 82
    level.layers["fg"].objects["rafImage"].y = -1161
    level.layers["fg"].objects["rafImage"].name = "rafImage"
    level.layers["fg"]:insert(level.layers["fg"].objects["rafImage"])

    level.layers["fg"].objects["rafInfo"] = display.newImageRect( imgSubFolder .. "rafael-info.jpeg",128,165 )
    level.layers["fg"].objects["rafInfo"].x = 235
    level.layers["fg"].objects["rafInfo"].y = -1163
    level.layers["fg"].objects["rafInfo"].name = "rafInfo"
    level.layers["fg"]:insert(level.layers["fg"].objects["rafInfo"])

    level:insert(level.layers["fg"])


    return level

end -- CreateLevel

